# -*- coding: utf-8 -*-
"""Day_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zbRb0rZjigZabwR9cYfH1Br3cdqiI3Lm
"""

a=10
print(a)
print(type(a))
print(id(a))

# @title Default title text
a=10.2
print(a)
print(type(a))

a=True
print(a)
print(type(a))

a="Atharva"
print(a)
print(type(a))

a='Atharva'
print(a)
print(type(a))

a=5+7j
print(a)
print(type(a))

print(int(10))
print(int(10.5))
print(int("10"))
print(int('10'))
print(int(True))
print(int(False))

print(float(10))
print(float(10.5))
print(float("10"))
print(float('10'))
print(float(True))
print(float(False))

print(bool(10))
print(bool(10.5))
print(bool("10"))
print(bool('10'))
print(bool(True))
print(bool(False))

a=3
b=5
e1=complex(a,b)
print(e1)
e2=2+6j
res=e1+e2
print(res)
print(complex(2,6j))

a=10
b=10
print(a is b)
x=True
y=True
print(x is y)

x="hello learning python is very easy!"
print('h' in x)

import math
r=int(input("enter the value: "))
res=math.pi*(r**2)
print (res)

x=input("Enter first number:")
y=input("Enter second number:")
x=int(x)
y=int(y)
print("The Sum:",x+y)

print("The Sum:",int(input("Enter first number:"))+int(input("Enter second number:")))

print("hello","world")
print("hello"+"world")
print("hello \n world")
print("hello\t world")
print("hello""world"*3)

print("Hello",end=' ')
print("Python",end=' ')
print("World")

a,b,c=10,20,30
print(a,b,c)
print(a,b,c,sep=",")
print(a,b,c,sep=":")

name="Atharva"
salary="30000"
company="TCS"
print("Hello{0} your salary is {1} and hired by :{2}".format(name,salary,company))
print("Hello{x} your salary is {y} and hired by :{z}".format(x=name,y=salary,z=company))

#find last digit of a number.
a=int(input("Enter a number:"))
res=a%10
print(res)

#Add 2 digits of a no.
no=int(input("Enter a number:"))
n1=no%10
no=no//10
n2=no%10
res=n1+n2
print("the sum of e digits are:",res)

#Add 3 digits of a no.
no=int(input("Enter a number:"))
n1=no%10
no=no//10
n2=no%10
no=no//10
n3=no%10
res=n1+n2+n3
print("the sum of e digits are:",res)

#Add 6 digits of a no.
no=int(input("Enter a number:"))
n1=no%10
no=no//10
n2=no%10
no=no//10
n3=no%10
no=no//10
n4=no%10
no=no//10
n5=no%10
no=no//10
n6=no%10
res=n1+n2+n3+n4+n5+n6
print("the sum of e digits are:",res)

#reverse 6 digits of a no.
no=int(input("Enter a number:"))
n1=no%10
no=no//10
n2=no%10
no=no//10
n3=no%10
no=no//10
n4=no%10
no=no//10
n5=no%10
no=no//10
n6=no%10
rev=n1*100000+n2*10000+n3*1000+n4*100+n5*10+n6*1
print("the reverse of digits are:",rev)

a=10
b=20
print("Before swapping a=",a,"b=",b)
temp=a
a=10
b=20
print("Before swapping a=",a,"b=",b)
temp=a
a=b
b=temp
print("After swapping a=",a,"b=",b)

a=10
b=20
a=a+b
b=a-b
a=a-b
print(a,b)

#average of 3 numbers
a=int(input("Enter first number: "))
b=int(input("Enter second number: "))
c=int(input("Enter third number: "))
avg=(a+b+c)/3 #answer with decimals
aveg=(a+b+c)//3 #answer without decimals
print(avg)
print(aveg)

# Basic Student Marksheet Design

print("-----------------------------------------------------------")
print("                   Atharva University                      ")
print("-----------------------------------------------------------")
print("Student Name: Atharva             Roll No.: 1004")
print("-----------------------------------------------------------")
print("Sr. no.   Subjects          Total Marks      Obtained Marks")
print("-----------------------------------------------------------")
# Printing subjects and marks
print("1.        Maths                 100              97")
print("2.        Science               100              90")
print("3.        English               100              93")
print("4.        Social Science        100              87")
print("5.        Hindi                 100              73")

# Calculating total and percentage
total_marks = 100 * 5
obtained_marks = 97 + 90 + 93 + 87 + 73
percentage = (obtained_marks / total_marks) * 100

# Printing total and percentage
print("-----------------------------------------------------------")
print("Total Marks: {}                ".format(obtained_marks))
print("Percentage: {}%                 ".format(int(percentage)))
print("-----------------------------------------------------------")