# -*- coding: utf-8 -*-
"""Day_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZEsKMKZh5YHbFCgqCl5wnVmEfX1Ugnbb
"""

#write lines
f=open("myfile.txt",'w')
f.write("Atharva \n")
f.write("Chandrashekhar \n")
f.write("Ghayal \n")
print("Write operation done sucessfuully")
f.close()

#writelines()
f=open("myfile.txt",'w')
l=["Sarthak\n","Arti\n","Chandrashekhar\n"]
f.writelines(l)
print("Write operation done sucessfuully")
f.close()

#read data from text files.
f=open("myfile.txt",'r')
data=f.read()
print(data)
f.close()
f=open("myfile.txt",'r')
data=f.read(12)
print(data)
f.close()

#readlines in text file.
f=open("myfile.txt"'r')
l1=f1.readlines()
print(l1)
for x in l1:
    print(x)
f.close()

#with statement.
with open("myfile.txt",'w') as f:
    f.write("Python\n")
    f.write("is\n")
    f.write("Easy\n")
    f.write("Language\n")
    print("is file closed?",f.closed)
print("Now is file closed?",f.closed)

#tell function
data="Learning python is very easy!!"
f=open("myfile.txt",'w')
f.write(data)
with open("myfile.txt",'r+') as f:
    filedata=f.read()
    print(filedata)
    print("Current cursor position is: ",f.tell())
    f.seek(15)
    print("Current cursor position is: ",f.tell())
    f.write("-Java-")
    f.seek(0)
    filedata=f.read()
    print(filedata)

#create 3 text files,add,write,append,read(Homework)

#check file exists or not.
import os
if os.path.exists("myfile.txt"):
    print("File exists",myfile.txt)
    f=open("myfile.txt",'r')
else:
    print("File not exists",myfile.txt)
    sys.exit(0)

# Write a program to print number of lines,words,characters present in the file.
lcount=wcount=ccount=0
for line in f:
  lcount =lcount+1
  ccount=ccount+len(line)
  words=line.split()
  wcount=wcount+len(words)

print("Total lines: ",lcount)
print("Total words: ",wcount)
print("Total characters: ",ccount)

# creating image replica.
f1=open("IMG-20250108-WA0002[1].jpg","rb")
f1=open("newIMG-20250108-WA0002[1].jpg","wb")
bytes=f1.read()
f2.write(bytes)
print(bytes)
print("New image is available")

# writing data to .csv file
import csv
with open("emp.csv",'w',newline='') as f:
    writer=csv.writer(f)
    w.writerow(["ENO","ENAME","ESALARY","EADDR"])
    n=int(input("Enter number of employees: "))
    for i in range(n):
        eno=int(input("Enter employee number: "))
        ename=input("Enter employee name: ")
        esalary=int(input("Enter employee salary: "))
        eaddr=input("Enter employee address: ")
        w.writerow([eno,ename,esalary,eaddr])
print("Data inserted sucessfully!!")

# reading data from.csv file
import csv
f=open("emp.csv",'r')
r=csv.reader(f)
data=list(r)
print(data)
for line in data:
  for word in line:
    print(word,"\t",end=" ")
  print()

import os
file_path="example.txt"
def write_to_file(file_path,content):
    with open(file_path,'w') as file:
        file.write(content)
    print(f,"Content written to {file_path}")

#Reading from a file.
def read_from_file(file_path):
        if os.path.exists(file_path):
            with open(file_path,'r') as file:
              content=file.read()
            print(f"Content of {file_path}:\n{content}")
        else:
            print(f"File '{file_path}' does not exists!")

# merge 2 sorted lists.
arr1=[1,3,5,6,7,8]
arr2=[2,4,6]
res=[]
i=0
k=0
j=0
for i in range(len(arr1)):
  if arr1[i] < arr2[j]:
  res.append(arr1[i])
  i=i+1;
  else:
  i=k
  j=i
  k=j

  if arr1[i] == arr2[j]:
    print(res)
print(res)