# -*- coding: utf-8 -*-
"""Day_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q233serqPUZ0dE3dU79Au0GWgZHt7MdW
"""

#All about functions.
""" A to Z--> 65 to 91.
    a to z--> 97 to 122.
    0-9-->48 to 57."""

#Methods of creating tuple.
t=()
print(type(t))
print(t)

t=tuple()
print(type(t))
print(t)

t(12,23,34,45,67)
print(type(t))
print(t)

t=12,23,45,56,67
print(type(t))
print(t)

t=eval(input("Enter a tuple: "))
l=len(t)
sum=0
for x in t:
  sum=sum+x
  print(sum)
  print(sum/l)

#insertion order in not preserved.
# duplicate values are not allowed in list.

s=set()
print(s)
print(type(s))
a={1234,23445,345445,3,3,23}
print(a)
print(type(a))

s=[10,20,30,40,50,10,30,20]
a=set(s)
print()

'''
remove()
clear()
pop()
len()
min()/max()
index()
sum()
'''

#all about Dictionaries
#insertion order is not preserved
#mutable
#are dynamic
#indexing and slicing not applicable
#growable in nature
d={}
print(d)
print(type(d))
#example.
d={101:"Atharva",102:"Sarthak",103:"Utkarsh",104:"YASH"}
print(d)
print(type(d))
#other method...
d[105]="Ashish"
print(d)

from os import name
#WAP to enter a name,and percentage maks in a dict and display info on screen.
rec={}
n=int(input("Enter number of students: "))
for i in range(1,n+1):
  name=(input("Enter name: "))
  percent=(input("Enter percentage: "))
  rec[name]=percent
print(rec)

d={101:"Atharva",102:"Sarthak",103:"Utkarsh",104:"YASH"}
del d[101]
print(d)

d={101:"Atharva",102:"Sarthak",103:"Utkarsh",104:"YASH"}
print(d[101])
print(d[102])
print(d[103])
print(d[104])
print(d.get(101))
print(d.get(400,"Guest"))
print(d[400])

#key and value function
d={101:"Atharva",102:"Sarthak",103:"Utkarsh",104:"YASH"}
print(d.keys())
for i in d.keys():
  print(i)

#key and value function
d={101:"Atharva",102:"Sarthak",103:"Utkarsh",104:"YASH"}
print(d.values())
for i in d.values():
  print(i)

#key and value function
d={101:"Atharva",102:"Sarthak",103:"Utkarsh",104:"YASH"}
print(d.items())
for k,v in d.items():
  print(k,'\t',v)

user_dict = {}
n = int(input("How many items do you want to add to the dictionary? "))
for _ in range(n):
    key = input("Enter the key: ")
    value = input("Enter the value: ")
    user_dict[key] = value
print("The dictionary you entered is:", user_dict)
a =(input("which key you want to delete: "))
del user_dict[a]
print(user_dict)

user_dict = {}
n = int(input("How many items do you want to add to the dictionary? "))
for i in range(n):
    key = input("Enter the key: ")
    value = input("Enter the value: ")
    user_dict[key] = value
print("The dictionary you entered is:", user_dict)
a =(input("Enter to check your key exists: "))
if(user_dict.get(a)==None):
  print("Does not exists")
else:
  print("exists")

user_dict = {}
n = int(input("How many items do you want to add to the dictionary? "))
for i in range(n):
    key = input("Enter the key: ")
    value = input("Enter the value: ")
    user_dict[key] = value
print("The dictionary you entered is:", user_dict)

user_dict = {}
n = int(input("How many items do you want to add to the dictionary? "))
for i in range(n):
    key = input("Enter the key: ")
    value = input("Enter the value: ")
    user_dict[key] = value
print("The dictionary you entered is:", user_dict)
rev={value: key for key, value in user_dict.items()}
print(rev)

#write a program to find the largest element in a list.
user_dict = []
n = int(input("How many items do you want to add to the list? "))
for i in range(n):
    key = input("Enter the key: ")
    value = input("Enter the value: ")
    user_dict[key] = value
print("The list you entered is:", user_dict)
i=user_dict[0]
j=user_dict[-1]
k=""
if j>i:
  i==j
  j==k
  k==i
  if
else:
  print("first value is greater!!")

def add(a,b):
   res1=x+y
   res2=x-y
   res3=x*y
   res4=x/y
   return res1,res2,res3,res4
#mul val in function
a=int(input())
b=int(input())
r1,r2,r3,r4=add(a,b)
print("Addition is ",r1)
print("Sub is ",r2)
print("Mul is ",r3)
print("Division is ",r4)
print(add(a,b))

#MENU driven program using elif

def add():
  a=int(input("Please enter a number: "))
  b=int(input("Please enter a number: "))
  res=a+b
  print(res)

def sub():
  a=int(input("Please enter a number: "))
  b=int(input("Please enter a number: "))
  res1=a-b
  print(res1)

def mul():
  a=int(input("Please enter a number: "))
  b=int(input("Please enter a number: "))
  res2=a*b
  print(res2)

def div():
  a=int(input("Please enter a number: "))
  b=int(input("Please enter a number: "))
  res=a/b
  print(res)


print("1. Addition")
print("2. Substraction")
print("3. Multiplication")
print("4. Division")
print("5. Exit")
n=int(input())

#When if is used we will come out after every iteration
if n==1:
  add()
elif n==2:
  sub()
elif n==3:
  mul()
elif n==4:
  div()
elif n==5:
  exit
else:
  print("Invalid Choice")

# Function using a while loop
def count_down(start):
    while start > 0:
        print(f"Counting down: {start}")
        start -= 1  # Decrease the counter
    print("Countdown complete!")
# Calling the function
count_down(5)

#positional Argument
def add(x,y):
  res=x+y
  print("x= ",x)
  print("y= ",y)
  print(res)

add(x=11,y=22)

#keyword argument
def add(x,y):
  res=x+y
  print("x= ",x)
  print("y= ",y)
  print(res)

add(y=22,x=11)

#default argument
def add(x,y=22):
  res=x+y
  print("x= ",x)
  print("y= ",y)
  print(res)

add(x=22,y=10)
print("\n")
add(a=22)

#default argument
def sum(*n):
  total=0
  for n1 in n:
    total =total+n1
  print("x= ",x)
  print("y= ",y)
  print(res)

add(x=22,y=10)
print("\n")
add(a=22)