# -*- coding: utf-8 -*-
"""Day_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CTn-TloSAOYlYa9AJashs4RHgp-UpTHM
"""

#command line arguments.
from sys import argv
print(type(argv))