# -*- coding: utf-8 -*-
"""Day-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FffnovzgmdytffCoj4k2Q1bhp0yxBD4p
"""

#nested for loops
for i in range(1,5):
    for j in range(1,5):
        print(i,end='')
    print()

#printing Patterns in nested for loop
n=1
for i in range(1,5):
  for j in range(1,5):
    print(n, end="\t")
    n+=1
  print()

n=33
for i in range(1,5):
  for j in range(1,5):
    print(chr(n),end="\t")
    n=n+1
  print()

# number pyramid using for loop
for i in range(1,5):
  for j in range(1,i+1):
    print(i,end="\t")
  print()

# * pyramid using nested for loop
for i in range(1,5):
  for j in range(1,i+1):
    print("*", end="\t")
  print()

#reverse * pyramid using nested forloop
#nested for loop
for i in range(5,0,-1):
  for j in range(1,i):
    print("*",end="")
  print()

sp=5
for i in range(1,5):
    for x in range(sp):
        print(" ",end="")
    for j in range(1,i+1):
        print("*",end="")
    print()
    sp=sp-1

#strings in python
#string slice in python.
s="Atharva"
print(s[0])
print(s[1])
print(s[2])
print(s[3])
print(s[4])
print(s[5])
print(s[:])
print(s[1:8])
print(s[1:5])
print(s[0:6:3])

#find function
a="Python is very Easy"
print(a.find("Python"))
print(a.find("is"))
print(a.find("Easy"))

#count function
a="ababababababababababababababababafhlahald"
print(a.count("a"))
print(a.count("ab"))
print(a.count("a",3,10))

#count function
a="ababababababababababababababababafhlahald"
print(a.replace("a","b"))
a1=a.replace("a","b")
print(a1)
print(a.count("ab"))
print(a.count("a",3,10))

#splitting in python
a="Python is very Easy"
print(a.split())
print(a.split("is"))
s="1-4-2025"
l=print(s.split("-"))

#upper,lower,swap,title,capitalize in pyhton
a="Python is very Easy"
print(a.upper())
print(a.lower())
print(a.swapcase())
print(a.title())
print(a.capitalize())

#startwith,endwith in python
a="Python is very Easy"
print(a.startswith("Python"))
print(a.endswith("Easy"))
print(a.endswith("is"))

#isalnum,isalpha,islower,isupper,istitle in python
a="Python is very Easy"
print(a.isalnum())
print(a.isalpha())
print(a.islower())
print(a.isupper())
print(a.istitle())

a=input("Enter a sentence:")
print(''.join(reversed(a)))

#join in list
a=['Nagpur','Pune','Mumbai','Delhi']
s=':'.join(a)
print(s)

#reverse a sentence
a=input("Enter a sentence:")
rev=""
for i in a:
    rev=i+rev
print(rev)

a=input("Enter a sentence:")
rev=""
s=a.split()
for i in s:
    rev=i+" "+rev
print(rev)

#reverse internal content of each word without functions in python
a=input("Enter a sentence:")
s=a.split()
rev=""
for i in s:
    rev=rev+i[::-1]+" "
print(rev)

# WAP to remove duplicate characters from the given input string in python.
a=input("Enter a sentence:")
b=""
for i in a:
    if i not in b:
        b=b+i
print(b)

mob=str(input("Enter your mobile number: "))
if len(mob)==10:
  if mob.isdigit():
    if mob[0]==6 and mob==[1]==7 and mob[2]==8:
      print("Your number is valid in india")
    else:
      print("Your number is not valid in india")
  else:
    print("Your number is not valid in india")
else:
  print("Your number is not valid in india")

#anagram
a="tea"
b="eatn"
count=0
a=a.upper()
b=b.upper()
for i in a:
  if i in b:
    count=count+1
    continue
  else:
    print("nahi hai")
    break
if count==3:
  print("Anagram")

#word palindrome
a=input("Enter a word: ")
rev=""
for i in a:
    rev=i+rev
if a == rev:
    print("ha hai!")
else:
  print("Nahi hai,barabar daal")

a=input("Enter a given sentence")
vowel_count = 0
consonant_count = 0
vowels = {'a', 'e', 'i', 'o', 'u'}
# Process each character in the sentence
for i in a:
    if i.isalpha():  # Check if the character is a letter
        if i.lower() in vowels:  # Check if it's a vowel
            vowel_count = 1
        else:  # If not a vowel, it's a consonant
            consonant_count += 1

# Print the counts
print(f"Number of vowels: {vowel_count}")
print(f"Number of consonants: {consonant_count}")

#pangrams
a = input("Enter a sentence: ")
b = set()
for char in a:
    if char.isalpha():
        b.add(char.lower())
if len(b) == 26:
    print("The sentence is a pangram!")
else:
    print("The sentence is not a pangram.")

#Check for Valid Palindromic String:
a= input("Enter a sentence: ")
b = []
for i in a:
    if i.isalnum():
        b.append(i.lower())
if b == b[::-1]:
    print("The sentence is a palindrome!")
else:
    print("The sentence is not a palindrome.")

#lists in python
a=[]
print(type(a))
print(a)

a=list()
print(type(a))
print(a)

a=[23,34,56,78,89,00]
print(type(a))
print(a)

l=eval(input("Enter any number: "))
print(l)
print(type(l))

n=[11,[2,3,4],33,[75,24,22],55]
print(n,"\n")
for x in n:
  print(x,"\n")
print(n[0])
print(n[1])
print(n[2])
print(n[3])
print(n[1][0])
print(n[3][2])

n=[[10,20,30],[40,50,60],[70,80,90]]
print(n)
for x in n:
  print(x)
for i in range (len(n)):
  for j in range (len(n[i])):
    print(n[i][j], end=" ")
  print()

# sorting in list.
n=[12,23,34,45,56]
n.sort()
print(n)
a=[20,23,34,35,67]
a.sort(reverse=True)
print(a)

#traversing all elements of list
a=[0,1,2,3,4,5,6,7,8,9]
i=0
while i<len(a):
  print(a[i])
  i+=1

#traversing all elements of list by using for loop
n=[0,1,2,3,4,5,6,7,8,9,10]
for n1 in n:
  print(n1)

#to display onlu even numbers
for i in range(2,100,2):
  print(i)

#Manipulating all elements of list
list=[]
list.append("A")
list.append("B")
list.append("C")
print(list)

#to add all elementsto list upto 100 which are divisible by 10
list=[]
for i in range(51):
  if i%10==0:
    list.append(i)
  print(list)